### ISSUE TITLE
Confirm validity of Gumbel softmax

### ISSUE THREAD

**Issue by axnedergaard** [coree/ChiNet#20]
I implemented the Gumbel Softmax in cgan.py:gumbel_softmax(). I am using matrix operations while they do more explicit loops in the Chinese et al. paper. We need to confirm that the calculation done in the gumbel_softmax() function is correct.

**Comment by niladell** [comment]
I was checking the current implementation, and I'm still unsure of the rationale behind this explicit approach. Yes, I kinda see the motivation behind, but I do feel like we can approach this as if instead of trying to obtain the output in the embedding space, we can get the output in the vocabulary/words space and then embed so. In fact, that's the approach we used on the previous project and also it's pretty much the standard when you try to do word prediction or text generation.

So, if we have in mind that **Gumbel Softmax** is just a relaxation of the **argmax**, I don't get why we don't still attach to the same typical approach of predicting words (in a classification kind of approach) instead of trying to predict things in their embedded form.

In any case I went on and implemented a version of that approach (https://github.com/coree/ChiNet/commit/fabc22e2838f53f85c624eb6d39f6294132c93ee) based on the vanilla description of the [Gumbel Softmax](https://arxiv.org/abs/1611.01144). The cool part about this implementation is that we do not need the nasty and _nan-prone_ temperature matrices. In fact, on this version the code runs _"properly"_ (no definition of the term properly provided) and it trains (aka. some loss goes down but that's all I can say)
